### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by wchristian** [Nexela/PickerBeltTools#14] opened 2019-06-16 03:06 UTC
Also reported here: https://mods.factorio.com/mod/PickerBeltTools/discussion/5d05b1da2aa591000b5bdcb6

```
19078.994 Error MainLoop.cpp:1183: Exception at tick 77207085: The mod Picker Belt Tools caused a non-recoverable error.
Please report this error to the mod author.

Error while running event PickerBeltTools::on_selected_entity_changed (ID 52)
__PickerBeltTools__/scripts/belt-highlight.lua:418: attempt to get length of local 'input' (a nil value)
stack traceback:
	__PickerBeltTools__/scripts/belt-highlight.lua:418: in function <__PickerBeltTools__/scripts/belt-highlight.lua:364>
	(...tail calls...)
	__PickerBeltTools__/scripts/belt-highlight.lua:534: in function <__PickerBeltTools__/scripts/belt-highlight.lua:364>
	(...tail calls...)
	__PickerBeltTools__/scripts/belt-highlight.lua:614: in function 'read_belts'
	__PickerBeltTools__/scripts/belt-highlight.lua:1060: in function 'highlight_belts'
	__PickerBeltTools__/scripts/belt-highlight.lua:1113: in function 'handler'
	__stdlib__/stdlib/event/event.lua:313: in function 'pcall'
	__stdlib__/stdlib/event/event.lua:333: in function 'dispatch_event'
	__stdlib__/stdlib/event/event.lua:411: in function <__stdlib__/stdlib/event/event.lua:367
```

**Comment by TheStaplergun** [comment] 2019-06-16 22:44
Duplicate of issue #12
Fixed in https://github.com/Nexela/PickerBeltTools/commit/382f76120a5876ba7d2f999412553a1c1753875a

**Closed as completed by TheStaplergun** 2019-06-16 22:44 UTC
Labels: duplicate

**Comment by wchristian** [comment] 2019-06-17 12:54
For bugs that are fixed but have not had the fix released i recommend keeping one issue open, with a label. Particularly when it's a bug that'll easily wipe out hours of progress.
